global:
  dagsterHome: "/opt/dagster/dagster_home"

daemon:
  image:
    # When a tag is not supplied for a Dagster provided image,
    # it will default as the Helm chart version.
    repository: "docker.io/dagster/dagster-celery-k8s:latest"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 0.5
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

webserver:
  image:
    # When a tag is not supplied for a Dagster provided image,
    # it will default as the Helm chart version.
    repository: "docker.io/dagster/dagster-celery-k8s:latest"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: 0.5
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

codelocations:
  - name: example
    image:
#     repository: "docker.io/dagster/dagster-celery-k8s:latest"
      repository: "dagster-example-user-code:v2"
      pullPolicy: IfNotPresent

    resources:
      requests:
        cpu: 0.5
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

    workers:
      - name: worker-1
        resources:
          requests:
            cpu: 0.5
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi



flower:
  image:
    repository: "docker.io/mher/flower"
    tag: "0.9.5"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    annotations: {}
    port: 5555



postgresql:
  enabled: true

  auth:
    database: test
    username: test
    password: test

  service:
    port: 5432

redis:
  enabled: true

  architecture: standalone

  auth:
    enabled: true
    password: "test"

  port: 6379

  brokerDbNumber: 0
  backendDbNumber: 0

minio:
  enabled: true

  defaultBuckets: "dagster"

  auth:
    rootUser: "admin"
    rootPassword: "helloworld"
