apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.name" . }}-celery-worker-env
  labels:
    app: {{ template "dagster.name" $ }}
    chart: {{ template "dagster.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  {{ include "dagster.shared_env" $ | nindent 2 }}
