{{ range $deployment := .Values.codelocations }}
{{ range $worker := $deployment.workers }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.name" $ }}-celery-{{- $deployment.name }}-{{- $worker.name }}
  labels:
    app: {{ template "dagster.name" $ }}
    chart: {{ template "dagster.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  celery.yaml: |
    execution:
      celery:
        broker:
          env: DAGSTER_CELERY_BROKER_URL
        backend:
          env: DAGSTER_CELERY_BACKEND_URL
{{/*        config_source: {{ merge $individualConfig $sharedConfig | toYaml | nindent 10 }}*/}}
---
{{- end }}
{{- end }}
