apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dagster.name" $ -}}-daemon
  labels:
    {{- include "dagster.labels" $ | nindent 4 }}
    component: dagster-daemon
    deployment: daemon
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "dagster.selectorLabels" $ | nindent 6 }}
      component: dagster-daemon
      deployment: daemon
  template:
    metadata:
      labels:
        {{- include "dagster.selectorLabels" $ | nindent 8 }}
        component: dagster-daemon
        deployment: daemon
      annotations:
        checksum/dagster-workspace: {{ include (print $.Template.BasePath "/configmap-workspace.yaml") . | sha256sum }}
        checksum/dagster-instance: {{ include (print $.Template.BasePath "/configmap-instance.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "dagster.serviceAccountName" $ }}
      automountServiceAccountToken: true
      containers:
        - name: {{ include "dagster.name" $ -}}-daemon
          imagePullPolicy: {{ .Values.daemon.image.pullPolicy }}
          image: {{ .Values.daemon.image.repository }}
          command: [
            "/bin/bash",
            "-c",
            "dagster-daemon run -w /dagster-workspace/workspace.yaml",
          ]
          envFrom:
            - configMapRef:
                name: {{ template "dagster.name" $ }}-daemon-env
            - configMapRef:
                name: {{ template "dagster.name" $ }}-daemon-env
            - secretRef:
                name: {{ include "dagster.postgresql.secretName" . }}
            - secretRef:
                name: {{ include "dagster.celery.secretName" . }}
          volumeMounts:
            - name: dagster-instance-yaml
              mountPath: "{{ $.Values.global.dagsterHome }}/dagster.yaml"
              subPath: dagster.yaml
            - name: dagster-workspace-yaml
              mountPath: "/dagster-workspace/workspace.yaml"
              subPath: workspace.yaml
          resources:
            {{- toYaml .Values.daemon.resources | nindent 12 }}
      volumes:
        - name: dagster-instance-yaml
          configMap:
            name: {{ template "dagster.name" $ }}-instance
        - name: dagster-workspace-yaml
          configMap:
            name: {{ template "dagster.name" $ }}-workspace
