apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dagster.postgresql.secretName" . }}
  labels:
    app: "{{ template "dagster.name" . }}"
    chart: "{{ template "dagster.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  POSTGRES_HOST: "{{ printf "%s-postgresql.%s" (include "dagster.name" .) .Release.Namespace | b64enc}}"
  POSTGRES_PORT: "{{ .Values.postgresql.service.port | toString | b64enc }}"
  POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword | b64enc }}"
  POSTGRES_DB: "{{ .Values.postgresql.postgresqlDatabase | b64enc }}"
  postgresql-password: "{{ .Values.postgresql.postgresqlPassword | b64enc }}"
