apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dagster.celery.secretName" . }}
  labels:
    app: "{{ template "dagster.name" . }}"
    chart: "{{ template "dagster.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  DAGSTER_CELERY_BROKER_URL: "{{ include "dagster.celery.broker_url" . | b64enc }}"
  DAGSTER_CELERY_BACKEND_URL: "{{ include "dagster.celery.backend_url" . | b64enc }}"
