apiVersion: v1
kind: Service
metadata:
  name: {{ template "dagster.name" . }}-flower-service
  labels:
    {{- include "dagster.labels" . | nindent 4 }}
    component: flower
spec:
  type: {{ .Values.flower.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.flower.service.port | default 5555 }}
      targetPort: 5555
      protocol: TCP
      name: flower
  selector:
    {{- include "dagster.selectorLabels" . | nindent 4 }}
    component: flower
